version: '3.8'

services:
  mpc_node_websocket_chat_server:
    build: .
    image: ${DOCKER_CONTAINER_IMAGE_NAME}
    container_name: ${DOCKER_CONTAINER_NAME}
    restart: always
    ports:
      - "${SERVER_NETWORK_SOCKET_PORT}:${SERVER_NETWORK_SOCKET_PORT}"
    environment:
      REDIS_HOST: ${REDIS_HOST_NAME}
      REDIS_PORT: ${DOCKER_CONTAINER_PORT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge